"""migrate message

Revision ID: c784fef2e960
Revises: ace5d82a71b6
Create Date: 2024-02-23 01:13:41.601372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c784fef2e960'
down_revision = 'ace5d82a71b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_of_pages', sa.Integer(), nullable=True))
        batch_op.drop_column('pages')
        batch_op.drop_column('details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pages', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('no_of_pages')

    # ### end Alembic commands ###
